### ISSUE TITLE
Possible bug in MultiDestinationFactory.java ?

### ISSUE THREAD

**Issue by andrewdparkin** [ot4i/perf-harness#1]
Hi

I think I found a bug in com.ibm.uk.hursley.perfharness.MultiDestinationFactory.  In the section below in the registerConfig() method, should the check for "destBase < destMax" actually be "destBase > destMax" ?  If I use the code as it is I can never create the range of topics even when using the examples given in the documentation, but after making that change everything works as expected.

Thanks

if (destMax > 0 && destBase < destMax) {
   destMax = destBase;
   Config.logger.warning("-dx must be >= -db");
}

**Comment by MartinRoss-IBM** [comment]
Thank you @andrewdparkin - I have made the change as you describe and submitted a pull request for my colleague @RobQuads  to buddy check. Do you have the example command that you ran when you encountered this issue?

**Comment by andrewdparkin** [comment]
Hi, thanks for looking into this.  The error can be reproduced with the following args (this was one of the possible configurations on page 18 of manual.pdf):

-tc com.ibm.uk.hursley.perfharness.jms.r11.Sender
-d QUEUETEST
-db 4 -dx 6 -dn 5

The resulting output is below:

Invalid parameter: -dn must be within the specified bounds of -db and -dx
09:20:19.257 [ControlThread1] ERROR com.ibm.uk.hursley.perfharness - The current configuration is not valid. Try re-running with -h to see available options.

A slightly different error occurs if I specifically pass in the destination factory class name:

-tc com.ibm.uk.hursley.perfharness.jms.r11.Sender
-d QUEUETEST
-db 4 -dx 6 -dn 5 -df com.ibm.uk.hursley.perfharness.MultiDestinationFactory

The resulting output is below:

Invalid parameter: -dx must be >= -db
09:12:51.213 [ControlThread1] ERROR com.ibm.uk.hursley.perfharness - The current configuration is not valid. Try re-running with -h to see available options.

Please let me know if you need any more details.
