### ISSUE TITLE
Perfharness does not handle long passwords properly.

### ISSUE THREAD

**Issue by trbryant2** [ot4i/perf-harness#14]
I'm trying to use Perfharness to connect to a queue manager that is hosted on the MQ on Cloud (MQoC) SAAS offering.  MQoC requires applications to connect using a userid and API key (effectively a password) that is auto-generated.  An auto-generated password looks something similar to the following:  r-3PVelSkpBDXA_omuTmM4t7mMm4ufLH2I7cVinpW7E3

(Not my actual password.)  

When I attempt to use that password I get an MQRC 2035 error.

This issue also happens when I attempt to connect to a queue manager that is hosted on RHEL.  If I set the password for the userid that I'm connecting with to the same complex string I get an error.  If I connect using a password that has been set to a less complex value, such as Ibm@Trb2 then things work fine.

MQoC does not provide an option to set a less complex API Key (password), so Perfharness needs to be able to connect with the more complex password that is being assigned.

Upon further investigation I've determined that Perfharness will successfully connect to a queue manager if a password is 12 characters or less.  The 2035 errors occur if a password is 13 characters or longer.

**Comment by stmassey** [comment]
This should work ok. Ive previously tested it with MQoC generated passwords. You do need to use the -jm true option to enable CSP authentication mode.

**Comment by trbryant2** [comment]
Thank you.  I was not familiar with the -jm option.  I tried it and was successful.
