### ISSUE TITLE
ClassNotFoundException : com.ibm.mq.MQException

### ISSUE THREAD

**Issue by Wajih09** [ot4i/perf-harness#23]
Hello I have an issue 
It compile well but when running i got an exception  Caused by: java.lang.ClassNotFoundException: com.ibm.mq.MQException 
in clazz = Class.forName(newvalue); at line 467 in Config.java 
is it a kind of connecion to a database issue ?
Can you help me please ?

![image](https://user-images.githubusercontent.com/112098136/193253620-6388965b-eee5-47e0-8a00-9bbc378d4f55.png)

**Comment by pharrishur** [comment]
You need the IBM MQ client classes on the classpath at runtime. In a Linux install with the default intallation location they will be here:
/opt/mqm/java/lib/com.ibm.mq.allclient.jar 

You can also download them from here (to support clients running on a host where there is no MQ install):
https://mvnrepository.com/artifact/com.ibm.mq/com.ibm.mq.allclient

**Comment by Wajih09** [comment]
Thank you for your reply
I imported that com.ibm.mq.allclient-9.3.0.0.jar to the project and add it to build path (C:\Users\a876965\PerfHarnessWorkSpace\PerfHarness\com.ibm.mq.allclient-9.3.0.0.jar)  but still have same exception :/ 
(I am using Windows 11 and IBM MQ Version 9.2)

![image](https://user-images.githubusercontent.com/112098136/193589508-c27a1910-30f9-4ca4-8ff2-2029ddeabb01.png)

**Comment by pharrishur** [comment]
That will enable you to build it, but you also need that jar in the classpath at runtime. Modify the classpath in the run configuration for PerfHarness. Outside of Eclipse you'd need to include it in the CLASSPATH environment variable or on the -cp java command line parameter.

**Comment by Wajih09** [comment]
Thank you sir
The exception is gone :)
