### ISSUE TITLE
MQJE001 completion code '2' reason '2035'

### ISSUE THREAD

**Issue by Wajih09** [ot4i/perf-harness#24]
Hello Everyone,
Thank you @pharrishur for your help on my last issue
I have fixed other exceptions related to SYSTEM.BKR.CONFIG channel later, but here I got an exception when running the programm :  MQJE001 completion code '2' reason '2035' 
I have followed an instruction in a forum telling to disable channel authorization (CHLAUTH) to allow all users to connect to MQ, which is enabled by default in the queue manager,
using commands : runmqsc  QManagerName     then       ALTER QMGR CHLAUTH(DISABLED)
    result    =>       1 : ALTER QMGR CHLAUTH(DISABLED)
                             AMQ8005I: The IBM MQ queue manager has changed

but the same exception is remaining

![image](https://user-images.githubusercontent.com/112098136/194065379-8f55f6aa-caaf-426c-8d7e-52a2f61a7aef.png)

**Comment by pharrishur** [comment]
If you check the error log for your queue manager you should see some indication of what the problem is there. Typically this is because you still have connection authentication enabled. Assuming you're using local OS userids (dis qmgr shows  CONNAUTH(SYSTEM.DEFAULT.AUTHINFO.IDPWOS)) you can make this optional (for testing purposes) by:

alter authinfo(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) authtype(IDPWOS) chckclnt(OPTIONAL)
refresh security(*) type(CONNAUTH)

Alternatively, you can supply a userid and password on the command line of PerfHarness with the -us and -pw parms.

**Comment by Wajih09** [comment]
Hi again,
The error log file confirms that is a matter of authentification :

[AMQERR01.LOG](https://github.com/ot4i/perf-harness/files/9746665/AMQERR01.LOG)

I persued 2 methods : yours at left and an other one from a forum on net at right (as mentioned in yellow in screenshot below )
Screenshot explanation : Commands wrote to console are framed in yellow and the received responses are framed in green and  translated from Frensh.
My queue manager is named "MQTEST" , I have restarted it manually from IBM MQ Explorer after every method and before running perfHarness, 
but I got always same issue about authentification.

![image](https://user-images.githubusercontent.com/112098136/194893506-54ca10a9-4df4-4ba4-9c6d-f1303c43375d.png)


Otherwise, in this second screenshot you can see the ID user + password configuration on IBM MQ Explorer : 

![image](https://user-images.githubusercontent.com/112098136/194890134-2a5c000d-5c9b-4704-90f7-a4cf8291295b.png)

Finally your last request about suppluying userid and password isn't quite clear, I supply them on the terminal in Eclipse you mean ? but when using -us and -pw command in terminal, it's not known as internal, should I add an environment variable

![image](https://user-images.githubusercontent.com/112098136/194892327-e2530302-dc50-4bb5-8183-0fe65ef8e5d0.png)

Thanks

**Comment by pharrishur** [comment]
-us and -pw are JMSPerfHarness program arguments, so are specified in the same way as e.g. -tc  in the program arguments section of the run configuration. You can see this panel in the readme on this site.  

It's possible you're not using the AUTHINFO object you altered. You can try disabling CONNAUTH altogether by issuing:
alter qmgr CONNAUTH('')
refresh security type(connauth)

**Comment by pharrishur** [comment]
Closing as stale.
