### ISSUE TITLE
ControlThread doesnt finish correctly when using fixed iterations(mg)

### ISSUE THREAD

**Issue by stmassey** [ot4i/perf-harness#7]
The ControlThread doesnt finish correctly when a specific number of iterations are specified. The individual threads complete when the required iterations have been executed, but the ControlThread doesnt end.

This is due to the logic in ControlThread.run() where its waiting for the workerThreadGroup.activeCount to reach zero. A number of JMS implementations launch additional threads when connections are made to remote systems which arent terminated when those connections are closed, thus we need to add some more intelligence to our thread detection.

**Comment by MartinRoss-IBM** [comment]
Fixed by pull request #8
