### ISSUE TITLE
How to interpret result? No documentation at all

### ISSUE THREAD

**Issue by panho66** [ot4i/perf-harness#9]
rateR=124.17,threads=5
rateR=127.70,threads=5
rateR=124.80,threads=5
Requestor3: STOP
Requestor1: STOP
totalIterations=14549,avgDuration=122.54,maxrateR=127.73

What is rateR means and also totalIterations and maxrateR?

This is same test run again two MQ using different nfs file system. Which one is better ?
totalIterations=54753,avgDuration=122.54,maxrateR=464.57
totalIterations=14549,avgDuration=122.54,maxrateR=127.73

**Comment by MartinRoss-IBM** [comment]
Hi panho - the default statistics reporting module is RollingAvgStats (https://github.com/ot4i/perf-harness/blob/master/PerfHarness/src/com/ibm/uk/hursley/perfharness/stats/RollingAvgStats.java).

If you run `java -cp <CLASSPATH> JMSPerfHarness -hf` you should see detailed help information, the last section should give some information on the RollingAvgStats:

```
com.ibm.uk.hursley.perfharness.stats.Statistics:
  ss    Statistics reporting period. (default: 10)
        Setting this to 0 will disable periodic reporting entirely.
  sp    Display per-thread iteration counts. (default: false)
        The infomation given per thread is the number of iterations (not a
        rate/sec) in the reporting period.
  sw    Statistical discard period (seconds). (default: 0)
        The given warmup period is excluded from the calculations of
        final summary.
  sc    Statistics module to use - options are BasicStats, ResponseTimeStats or RollingAvgStats. (default: RollingAvgStats)

  sd    Sets what is reported as totalDuration. (default: normal)
        "normal" = from 1st iteration to last iteration, excluding setup/takedown.
        "tlf" = Time to Last Fire, from start of main thread till last iteration completes
        (includes setup time but not takedown).

com.ibm.uk.hursley.perfharness.stats.RollingAvgStats:
  sr    Rolling average period (seconds). (default: 30)
        Performance is sampled every second, the number reported is the
        average over the last rolling average period.  During the first period, the
        figure reported is the average over the actual number of seconds elapsed.

com.ibm.uk.hursley.perfharness.cmd.Command:
  cmd_c Command module to use. (default: DummyCommandProcessor)
```

There should be an extra description under the RollingAvgStats which is missing above but should be addressed with the following pull request I have just submitted for my colleague to review:
https://github.com/ot4i/perf-harness/pull/10

When that pull request is in the help information should additionally show:

```
com.ibm.uk.hursley.perfharness.stats.RollingAvgStats:
Prints the average of performance over the last 30 seconds on a periodic basis.  The
final summary is the average duration of the WorkerThreads and the maximum
rolling average achieved during that period.

  sr    Rolling average period (seconds). (default: 30)
        Performance is sampled every second, the number reported is the
        average over the last rolling average period.  During the first period, the
        figure reported is the average over the actual number of seconds elapsed.
```

Other options for statistic reporting modules are BasicStats and ResponseTimeStats.

I will look to improve the documentation here as I agree that it is lacking but hopefully the above should give you the information you need on the output.

Your first test has the result `totalIterations=54753,avgDuration=122.54,maxrateR=464.57` which indicates that 54753 messages have been sent/received (depending on how you invoked PerfHarness), that the average duration of each thread was 122.54 seconds and the maximum rolling average (default 30 second) achieved over the period was 464.57.

Your second test has the result `totalIterations=14549,avgDuration=122.54,maxrateR=127.73` which indicates that 14549 messages have been sent/received (depending on how you invoked PerfHarness), that the average duration of each thread was 122.54 seconds and the maximum rolling average (default 30 second) achieved over the period was 127.73.

So as long as the tests are comparable the results indicate that the first test showed a higher message rate was achieved.

**Comment by panho66** [comment]
thanks

**Comment by aks3333** [comment]
Hi all, Can you help me how to increase message rate via this tool/command, I am only getting below result after executing this command - 
./cph -tc Requester -nt 5 -jb QMGR1 -jh 10.x.x.x -jp 1416 -jc SYSTEM.DEF.SVRCONN -iq INPUTQ -oq OUTPUTQ -db 1 -rl 300 -jt mqc -pp -tx -ms 4194304
./cph -tc Responder -nt 5 -jb QMGR1 -jh 10.x.x.x -jp 1416 -jc SYSTEM.DEF.SVRCONN -iq INPUTQ -oq OUTPUTQ -db 1 -rl 300 -jt mqc -pp -tx

Result - 
totalIterations=1003,totalSeconds=305.84,avgRate=3.28

**Comment by pharrishur** [comment]
> 
> 
> Hi all, Can you help me how to increase message rate via this tool/command, I am only getting below result after executing this command -
> ./cph -tc Requester -nt 5 -jb QMGR1 -jh 10.x.x.x -jp 1416 -jc SYSTEM.DEF.SVRCONN -iq INPUTQ -oq OUTPUTQ -db 1 -rl 300 -jt mqc -pp -tx -ms 4194304
> ./cph -tc Responder -nt 5 -jb QMGR1 -jh 10.x.x.x -jp 1416 -jc SYSTEM.DEF.SVRCONN -iq INPUTQ -oq OUTPUTQ -db 1 -rl 300 -jt mqc -pp -tx
> 
> Result -
> totalIterations=1003,totalSeconds=305.84,avgRate=3.28

This issue is closed and unrelated but to answer your question:
The tool is being run unrated (you're not specifying the -rt parm on the requester), so the results you're getting indicate the fastest you can put and get persistent 4MB messages to a single queue using 5 threads in your environment. You can try increasing the number of threads, but I suspect at the rates you're getting that's not going to help. Spreading the load across multiple queues will reduce locking (e.g. specify -oq REPLY -iq REQUEST -db 1 -dx 5 -dn 1 to spread the messages across queues REQUEST1-REQUEST5 & REPLY1-REPLY5).  The tool is reporting your performance, as designed, you now need to investigate why the rate is that low, check the CPU utilisation of the machines, the network performance and the performance of the filesystem hosting the MQ recovery log. You can find performance rports and other helpful documnetation on our MQ performance GitHub site here: https://ibm-messaging.github.io/mqperf/

**Comment by aks3333** [comment]
Hi @pharrishur 
thanks a lot for your reply, I have tried as per given instruction from you and getting same result. 
would you suggest any thing else like finetunning over the Linux VM etc ? or this is just a limitation of this CPH tool where we can only get below result.

./cph -tc Requester -nt 5 -jb RDQM1 -jh 10.x.x.x -jp 1416 -jc SYSTEM.DEF.SVRCONN -iq INPUTQ -oq OUTPUTQ -db 1 -dx 5 -dn 1 -rl 300 -jt mqc -pp -tx -ms 4194304
totalIterations=1032,totalSeconds=305.09,avgRate=3.38

./cph -tc Responder -nt 5 -jb RDQMDRHAQM2 -jh 10.x.x.x-jp 1416 -jc SYSTEM.DEF.SVRCONN -iq INPUTQ -oq OUTPUTQ -db 1 -dx 5 -dn 1 -rl 300 -jt mqc -pp -tx
totalIterations=1032,totalSeconds=308.98,avgRate=3.34

where below is utlization result during test run -  

Disk IO - is 16%
CPU is 22% where 2 CPU are allocated
Network utlization is 7GB
Memory - 35%, where 8GB memory allocated.

**Comment by stmassey** [comment]
This is a closed issue and your concern relates to the cph test harness. Can you raise an issue at: https://github.com/ibm-messaging/mq-cph
You might want to add information such as the configuration youve applied to your QM, results for varying numbers of requester clients (ensuring that #responders > #requesters), latency between clients and QM, details of your IO subsystem, results for NP messaging etc.

**Comment by aks3333** [comment]
thanks Sam, we are raising the new request. sorry for writting on closed issue.
